// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJWzJRqvOHvoYwcMTL6jAhFCMj2bsFZDE',
    appId: '1:435533952242:web:04543221ec2b0cb7004c6b',
    messagingSenderId: '435533952242',
    projectId: 'piv-fertilizer-app',
    authDomain: 'piv-fertilizer-app.firebaseapp.com',
    storageBucket: 'piv-fertilizer-app.firebasestorage.app',
    measurementId: 'G-3VS70EMTWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcn3v0PcMwc1jQe7S427oteWsq1q_F2_s',
    appId: '1:435533952242:android:4b2d0f67ad239bd9004c6b',
    messagingSenderId: '435533952242',
    projectId: 'piv-fertilizer-app',
    storageBucket: 'piv-fertilizer-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUWgSXb-CzTFuwdCnNQnbnKKH_WFtzDYA',
    appId: '1:435533952242:ios:84cc04c427d1f9f8004c6b',
    messagingSenderId: '435533952242',
    projectId: 'piv-fertilizer-app',
    storageBucket: 'piv-fertilizer-app.firebasestorage.app',
    androidClientId: '435533952242-2am4np65t8ceg86mlabfd3hailc4ln1d.apps.googleusercontent.com',
    iosClientId: '435533952242-ghv5fujaiq52p5r3d9bounsugmeh5bsa.apps.googleusercontent.com',
    iosBundleId: 'com.piv.fertilizer.pivApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUWgSXb-CzTFuwdCnNQnbnKKH_WFtzDYA',
    appId: '1:435533952242:ios:efe0855ee802f4a8004c6b',
    messagingSenderId: '435533952242',
    projectId: 'piv-fertilizer-app',
    storageBucket: 'piv-fertilizer-app.firebasestorage.app',
    iosBundleId: 'com.piv.fertilizer.pivApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJWzJRqvOHvoYwcMTL6jAhFCMj2bsFZDE',
    appId: '1:435533952242:web:9c4b0fda0fd9b252004c6b',
    messagingSenderId: '435533952242',
    projectId: 'piv-fertilizer-app',
    authDomain: 'piv-fertilizer-app.firebaseapp.com',
    storageBucket: 'piv-fertilizer-app.firebasestorage.app',
    measurementId: 'G-2NQSJ5FE43',
  );
}